import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
test("all CRM browser routes proxy to the server and no longer import D1",async()=>{const [data,register,landing,config,hosting]=await Promise.all([read("../app/api/data/route.ts"),read("../app/api/register/route.ts"),read("../app/landing/[slug]/page.tsx"),read("../app/api/social/_config.ts"),read("../.openai/hosting.json")]);for(const source of [data,register,landing,config])assert.doesNotMatch(source,/drizzle|D1Database|getDb|\.prepare\(/);assert.match(data,/proxySocialRequest/);assert.match(register,/routine-leads/);assert.match(landing,/resolveSocialListenerConfig/);assert.match(hosting,/"d1": null/)});
test("required SQL Server environment variables are documented without secrets",async()=>{const env=await read("../.env.example");for(const key of ["DB_SERVER","DB_PORT","DB_NAME","DB_USER","DB_PASSWORD","DB_ENCRYPT","DB_TRUST_SERVER_CERTIFICATE"])assert.match(env,new RegExp(`^${key}=`,"m"));assert.doesNotMatch(env,/DB_PASSWORD=.+/)});
test("schema contains normalized form tables, social automation relationships, indexes, transactions and CRUD procedures",async()=>{const [core,crud,automation]=await Promise.all([read("../sql/001_social_listener.sql"),read("../sql/002_crud_delete.sql"),read("../sql/003_social_crm_automation.sql")]);for(const table of ["Leads","Campaigns","LandingPages","Webinars","LeadRoutineEvents","SocialChannelConfigurations"])assert.match(core,new RegExp(`CREATE TABLE dbo\\.${table}`));for(const table of ["SocialPlatforms","SocialAccounts","SocialCampaigns","SocialConversations","SocialInteractions","Opportunities"])assert.match(automation,new RegExp(`CREATE TABLE dbo\\.${table}`));assert.match(core,/FOREIGN KEY \(CampaignId\)/);assert.match(core,/BEGIN TRANSACTION/);assert.match(automation,/SocialCampaign_ClaimDue/);for(const procedure of ["SocialLead_Delete","Campaign_Delete","LandingPage_Delete","Webinar_Delete"])assert.match(crud,new RegExp(`PROCEDURE dbo\\.${procedure}`));assert.match(crud,/IX_Leads_Email/)});
test("repository binds typed parameters instead of interpolating form values",async()=>{const source=await read("../social/sql-server.mjs");assert.match(source,/request\.input\("Name", this\.sql\.NVarChar/);assert.match(source,/request\.input\("Email", this\.sql\.NVarChar/);assert.match(source,/\.execute\("dbo\.SocialLead_Create"\)/);assert.doesNotMatch(source,/query\(`[^`]*\$\{/)});
test("every application form has a documented table mapping",async()=>{const mapping=await read("../docs/form-table-mapping.md");for(const form of ["Lead create/edit","Lead stage","AI/manual campaign","Landing page","Webinar","Webinar registration","Social channel settings","Social webhook"])assert.ok(mapping.includes(form),`${form} mapping is missing`)});
